### ISSUE TITLE
When I try to run the tests, they do not run against the local version of apollo-cursor-pagination

### ISSUE THREAD

**Issue by quietgopher** [FleekHQ/apollo-cursor-pagination#36]
Hi!  I'm making changes to a fork of apollo-cursor-pagination.  When I follow the instructions to run tests in the test-app, it does not appear that the test-app is using the local code base.  E.g. I'll introduce "throw Error(...)" into custom-pagination.js and the tests still pass.  It looks like it's coded for the local connection code to be used but its not working locally.

**Comment by dmerrill6** [comment]
Hi @quietgopher !

Sorry for the late response. Totally missed the notification.

The problem might be happening because the test-app imports the package using npm link (`"apollo-cursor-pagination": "file:../../",` in test-app's `package.json`).

If you are still having this issue, it's worth trying running `yarn link` in the root folder and then `yarn link apollo-cursor-pagination` in the test-app folder, and then running `yarn install` in the test-app.
